export const COLORS = {
  navy: '#0A1628',
  navyLight: '#1B2D4A',
  blue: '#2B7FFF',
  blueLight: '#5B9FFF',
  ivory: '#FAF7F2',
  ivoryWarm: '#F5F0E8',
  graphite: '#3A3A3A',
  graphiteLight: '#6B6B6B',
  oak: '#C4A882',
  oakDark: '#8B7355',
  platinum: '#C0C0C0',
  platinumLight: '#E8E8E8',
  goldSubtle: '#C9A96E',
  white: '#FFFFFF',
  black: '#000000',
} as const;

export const IMAGES = {
  building: {
    exteriorPeople: '/images/building/exterior-people.jpeg',
    exteriorClean: '/images/building/exterior-clean.jpeg',
    receptionPeople: '/images/building/reception-people.jpeg',
    receptionClean: '/images/building/reception-clean.jpeg',
    studyCafePeople: '/images/building/study-cafe-people.jpeg',
    studyCafeClean: '/images/building/study-cafe-clean.jpeg',
    careerLabPeople: '/images/building/career-lab-people.jpeg',
    careerLabClean: '/images/building/career-lab-clean.jpeg',
    studioPeople: '/images/building/studio-people.jpeg',
    studioClean: '/images/building/studio-clean.jpeg',
    birdsEye: '/images/building/birds-eye.jpeg',
  },
  cards: {
    basic: '/images/cards/basic.jpeg',
    pro: '/images/cards/pro.jpeg',
    premium: '/images/cards/premium.jpeg',
    platinum: '/images/cards/platinum.png',
    basicVisualWater: '/images/cards/basic-visual-water.jpeg',
    proVisualComparison: '/images/cards/pro-visual-comparison.jpeg',
    proVisualSmoke: '/images/cards/pro-visual-smoke.jpeg',
    proVisualBokeh: '/images/cards/pro-visual-bokeh.jpeg',
    proVisualMacro: '/images/cards/pro-visual-macro.jpeg',
    premiumVisualUnboxing: '/images/cards/premium-visual-unboxing.jpeg',
    premiumVisualBokeh: '/images/cards/premium-visual-bokeh.jpeg',
  },
  logo: {
    square: '/images/logo/logo-square.jpeg',
    horizontal: '/images/logo/logo-horizontal.jpeg',
    transparent: '/images/logo/logo-transparent.png',
  },
} as const;

export const NAV_LINKS = [
  { label: 'Spatii', href: '/spaces' },
  { label: 'Abonamente', href: '/membership' },
  { label: 'Career Lab', href: '/career-lab' },
  { label: 'Invata', href: '/learn' },
  { label: 'Despre', href: '/results' },
  { label: 'Contact', href: '/contact' },
] as const;

export const MEMBERSHIP_TIERS = [
  {
    id: 'basic',
    name: 'Basic',
    price: 149,
    tagline: 'Primul pas in ecosistem.',
    color: 'ivory',
    recommended: false,
    features: [
      'Acces Study Cafe',
      'Mini Library',
      'Panou Oportunitati',
      'Evenimente comunitare',
      'Wi-Fi premium',
      'Smart Card Basic',
    ],
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 499,
    tagline: 'Dezvoltare practica. Rezultate concrete.',
    color: 'navy',
    recommended: true,
    features: [
      'Tot ce include Basic',
      '2 workshopuri/luna incluse',
      'Career Lab (1 sesiune/luna)',
      'Team Project Room',
      'Project Studio (2h/luna)',
      'Interview Room',
      'Smart Card Pro',
    ],
  },
  {
    id: 'premium',
    name: 'Premium',
    price: 998,
    tagline: 'Mentorat personal. Strategie. Excelenta.',
    color: 'black',
    recommended: false,
    features: [
      'Tot ce include Pro',
      'Mentor personal dedicat',
      '4 workshopuri/luna incluse',
      'Career Lab (2 sesiuni/luna)',
      'Project Studio (5h/luna)',
      'Plan de dezvoltare personalizat',
      'Raport lunar de progres',
      'Smart Card Premium',
    ],
  },
] as const;
